CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	email VARCHAR (100) UNIQUE NOT NULL,
	PASSWORD VARCHAR(120) NOT NULL,
	ADMIN BOOLEAN DEFAULT FALSE NOT NULL,
	active BOOLEAN DEFAULT TRUE NOT NULL
)